services:
  api:
    container_name: deckify-api
    build: 
      context: ./backend
    ports:
      - 8000:8000
    environment:
      TOKEN_SECRET: 'supersecretkey'
      SHOW_SQL: false
      SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://admin:admin@db:3306/knock_bank_db'
    depends_on:
      - db

  web:
    container_name: deckify-web
    build: 
      context: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - api

  db:
    image: postgres:latest
    container_name: deckify-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: deckify
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
